- gui/src/components/ImageInput.tsx
- gui/src/components/Img2Img.tsx
- gui/src/components/Inpaint.tsx
- gui/src/components/MaskCanvas.tsx
- gui/src/config.ts
- gui/src/main.tsx
- gui/src/state.ts
> persist source and mask

- api/onnx_web/image.py
- api/onnx_web/serve.py
- gui/src/api/client.ts
- gui/src/components/Inpaint.tsx
- gui/src/components/MaskCanvas.tsx
- gui/src/components/NumericField.tsx
- gui/src/components/OnnxError.tsx
- gui/src/components/OnnxWeb.tsx
- gui/src/components/OutpaintControl.tsx
- gui/src/main.tsx
- gui/src/state.ts
> outpainting

- README.md
- api/onnx_web/image.py
- api/onnx_web/serve.py
- gui/src/api/client.ts
- gui/src/components/Inpaint.tsx
- gui/src/state.ts
- gui/src/strings.ts
- fixes #52 
- fixes #53 
- TODO: #55
> blend edges and fill options for inpainting/outpainting

- .gitlab-ci.yml
- api/dev-requirements.txt
- api/onnx_web/chain/base.py
- api/onnx_web/chain/blend_img2img.py
- api/onnx_web/chain/blend_inpaint.py
- api/onnx_web/chain/correct_gfpgan.py
- api/onnx_web/chain/persist_disk.py
- api/onnx_web/chain/persist_s3.py
- api/onnx_web/chain/reduce_crop.py
- api/onnx_web/chain/reduce_thumbnail.py
- api/onnx_web/chain/source_noise.py
- api/onnx_web/chain/source_txt2img.py
- api/onnx_web/chain/upscale_outpaint.py
- api/onnx_web/chain/upscale_resrgan.py
- api/onnx_web/chain/upscale_stable_diffusion.py
- api/onnx_web/device_pool.py
- api/onnx_web/diffusion/load.py
- api/onnx_web/diffusion/run.py
- api/onnx_web/onnx/onnx_net.py
- api/onnx_web/output.py
- api/onnx_web/params.py
- api/onnx_web/serve.py
- onnx-web.code-workspace
> support multiple cuda devices

- api/onnx_web/chain/upscale_outpaint.py
- api/onnx_web/diffusion/load.py
- api/onnx_web/diffusion/run.py
- fixes #27 
- except for upscale
- downloads the community pipeline
- need to include or cache
> enable LPW

- api/onnx_web/chain/blend_img2img.py
- api/onnx_web/chain/blend_inpaint.py
- api/onnx_web/chain/source_txt2img.py
- api/onnx_web/chain/upscale_outpaint.py
- api/onnx_web/chain/utils.py
- api/onnx_web/diffusion/load.py
- api/onnx_web/diffusion/run.py
- api/onnx_web/params.py
- api/onnx_web/serve.py
- docs/dev-test.md
- gui/src/client.ts
- gui/src/components/LoadingCard.tsx
- gui/src/components/control/ModelControl.tsx
- gui/src/state.ts
Enabling the long prompt weighting pipeline has broken a number of things (#99, #101). Make it optional.
> make LPW a request parameter

- api/onnx_web/device_pool.py
- api/onnx_web/serve.py
- api/onnx_web/utils.py
- gui/src/strings.ts
> add option to use any platform

- api/onnx_web/chain/base.py
- api/onnx_web/chain/blend_inpaint.py
- api/onnx_web/chain/upscale_outpaint.py
- api/onnx_web/chain/utils.py
- api/onnx_web/diffusion/run.py
- api/onnx_web/params.py
- api/onnx_web/serve.py
- api/params.json
- gui/src/client.ts
- gui/src/components/input/QueryList.tsx
- gui/src/components/tab/Inpaint.tsx
- gui/src/state.ts
> make tile order a parameter

- api/logging.yaml
- api/onnx_web/chain/base.py
- api/onnx_web/chain/blend_img2img.py
- api/onnx_web/chain/blend_inpaint.py
- api/onnx_web/chain/correct_gfpgan.py
- api/onnx_web/chain/source_txt2img.py
- api/onnx_web/chain/upscale_outpaint.py
- api/onnx_web/chain/upscale_stable_diffusion.py
- api/onnx_web/convert/__main__.py
- api/onnx_web/device_pool.py
- api/onnx_web/diffusion/load.py
- api/onnx_web/diffusion/run.py
- api/onnx_web/hacks.py
- api/onnx_web/upscale.py
- gui/src/components/LoadingCard.tsx
> chain pipeline progress

- api/onnx_web/__init__.py
- api/onnx_web/chain/base.py
- api/onnx_web/chain/blend_img2img.py
- api/onnx_web/chain/blend_inpaint.py
- api/onnx_web/chain/blend_mask.py
- api/onnx_web/chain/correct_codeformer.py
- api/onnx_web/chain/correct_gfpgan.py
- api/onnx_web/chain/persist_disk.py
- api/onnx_web/chain/persist_s3.py
- api/onnx_web/chain/reduce_crop.py
- api/onnx_web/chain/reduce_thumbnail.py
- api/onnx_web/chain/source_noise.py
- api/onnx_web/chain/source_txt2img.py
- api/onnx_web/chain/upscale_outpaint.py
- api/onnx_web/chain/upscale_resrgan.py
- api/onnx_web/chain/upscale_stable_diffusion.py
- api/onnx_web/diffusion/load.py
- api/onnx_web/diffusion/run.py
- api/onnx_web/serve.py
- api/onnx_web/server/device_pool.py
- api/onnx_web/server/hacks.py
- api/onnx_web/server/model_cache.py
- api/onnx_web/server/upscale.py
- api/onnx_web/utils.py
This should help reduce memory leaks, especially models in VRAM.
- fixes #124 
- fixes #134
> add model cache

- api/onnx_web/chain/base.py
- api/onnx_web/params.py
- api/onnx_web/serve.py
- api/onnx_web/server/upscale.py
- api/params.json
- gui/src/client.ts
- gui/src/components/control/UpscaleControl.tsx
- gui/src/state.ts
> add parameter to run correction before upscaling

- .gitlab-ci.yml
- api/onnx_web/convert/__main__.py
- api/onnx_web/convert/diffusion/diffusers.py
- api/onnx_web/convert/diffusion/original.py
- api/onnx_web/convert/diffusion/textual_inversion.py
> check for index file during model conversion

- api/onnx_web/convert/__main__.py
- api/onnx_web/convert/diffusion/diffusers.py
- api/onnx_web/convert/diffusion/lora.py
- api/onnx_web/convert/diffusion/original.py
- api/onnx_web/convert/diffusion/textual_inversion.py
- api/onnx_web/convert/utils.py
- api/onnx_web/diffusers/load.py
- api/schemas/extras.yaml
- docs/converting-models.md
- docs/user-guide.md
> feat(api): blend LoRAs and Textual Inversions from extras file

- api/onnx_web/diffusers/load.py
- api/onnx_web/diffusers/utils.py
- api/onnx_web/server/api.py
- api/onnx_web/worker/command.py
- api/onnx_web/worker/context.py
- api/onnx_web/worker/pool.py
- api/onnx_web/worker/worker.py
- gui/src/client/api.ts
- gui/src/client/local.ts
- gui/src/components/ImageHistory.tsx
- gui/src/components/card/ErrorCard.tsx
- gui/src/components/card/ImageCard.tsx
- gui/src/components/card/LoadingCard.tsx
- gui/src/components/card/RetryCard.tsx
- gui/src/components/tab/Blend.tsx
- gui/src/components/tab/Img2Img.tsx
- gui/src/components/tab/Inpaint.tsx
- gui/src/components/tab/Txt2Img.tsx
- gui/src/components/tab/Upscale.tsx
- gui/src/state.ts
- gui/src/strings/de.ts
- gui/src/strings/en.ts
- gui/src/strings/es.ts
- gui/src/strings/fr.ts
> image errors and retry

- .gitlab-ci.yml
- api/onnx_web/convert/__main__.py
- api/onnx_web/convert/diffusion/diffusers.py
- api/onnx_web/diffusers/utils.py
- fixes #202 
I don't really have a frame of reference for this, so testing will be tricky. Based on https://github.com/huggingface/transformers/blob/main/src/transformers/models/clip/modeling_clip.py#L683 and https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/sd_hijack_clip.py#L301, this should be how CLIP skip works.
> add support for CLIP skip

- api/onnx_web/diffusers/load.py
- docs/server-admin.md
> feat(api): add flag for ORT float16 optimizations

- .vscode/launch.json
- README.md
- api/onnx_web/convert/diffusion/lora.py
- api/onnx_web/main.py
- api/onnx_web/worker/command.py
- api/onnx_web/worker/pool.py
- api/onnx_web/worker/utils.py
- api/requirements/amd-linux-nightly.txt
- api/requirements/amd-linux.txt
- api/requirements/amd-windows.txt
- api/requirements/cpu-nightly.txt
- api/requirements/cpu.txt
- api/requirements/nvidia-nightly.txt
- api/requirements/nvidia.txt
- api/schemas/extras.yaml
- docs/dev-test.md
- docs/user-guide.md
- fixes #276 
- fixes #283 
- fixes #284 
- might even take care of #286
> fix progress queue

- api/onnx_web/__init__.py
- api/onnx_web/convert/diffusion/lora.py
- api/onnx_web/diffusers/run.py
- api/onnx_web/diffusers/upscale.py
- api/onnx_web/output.py
- api/onnx_web/params.py
- api/onnx_web/server/api.py
- api/onnx_web/server/load.py
- api/onnx_web/server/params.py
- api/onnx_web/worker/pool.py
- api/onnx_web/worker/worker.py
- api/params.json
- gui/Makefile
- gui/examples/config.json
- gui/src/client/api.ts
- gui/src/components/control/HighresControl.tsx
- gui/src/components/control/ImageControl.tsx
- gui/src/components/control/UpscaleControl.tsx
- gui/src/components/tab/Txt2Img.tsx
- gui/src/config.ts
- gui/src/main.tsx
- gui/src/state.ts
- gui/src/strings/de.ts
- gui/src/strings/en.ts
- gui/src/strings/es.ts
- gui/src/strings/fr.ts
> highres fix

- README.md
- api/entry.py
- api/onnx_web/convert/__main__.py
- api/onnx_web/convert/diffusion/lora.py
- api/onnx_web/convert/diffusion/original.py
- api/onnx_web/main.py
- api/onnx_web/server/admin.py
- api/onnx_web/server/api.py
- api/onnx_web/server/context.py
- api/onnx_web/worker/context.py
- api/onnx_web/worker/pool.py
- api/onnx_web/worker/worker.py
- gui/src/client/api.ts
- gui/src/client/local.ts
- gui/src/components/control/ModelControl.tsx
- gui/src/strings/de.ts
- gui/src/strings/en.ts
- gui/src/strings/es.ts
- gui/src/strings/fr.ts
> add admin endpoint to restart image workers

- api/onnx_web/diffusers/run.py
- api/onnx_web/params.py
> add support for negative embeds

- api/onnx_web/chain/base.py
- api/onnx_web/chain/source_txt2img.py
- api/onnx_web/chain/tile.py
- api/onnx_web/chain/upscale_outpaint.py
- api/onnx_web/diffusers/run.py
- api/onnx_web/image/utils.py
- api/onnx_web/server/api.py
Will require previous PR to be merged
> Tiled inpaint

- api/onnx_web/diffusers/utils.py
fixes https://github.com/ssube/onnx-web/issues/440
> fixes support for multiple wildcards in one token
